Install the dependencies-
sudo apt-get install md5deep
sudo apt-get install john
wget http://scrapmaker.com/data/wordlists/dictionaries/rockyou.txt


Run the Honeyword system-
g++ ib1.cpp -lcrypto -lssl
./a.out

Give the input of k
Give the input of 10 usernames and passwords.



Then,for task 2-
john --wordlist=rockyou.txt hashFile.txt
sudo john --show hashFile.txt


